---
- name: Configure Linux host
  hosts: all
  become: true
  roles:
    - base

- name: Setup users
  hosts: all
  become: true
  roles:
    - users

- name: Configure web_servers
  hosts: all
  become: true
  roles:
    - web_servers

  # Handlers ====================================
  handlers:
    # - name: Restart nfs
    #   ansible.builtin.systemd:
    #     name: nfs-server
    #     state: restarted
    #     enabled: true
    #     daemon_reload: true
    #   listen: restart_nfs

    # - name: Restart rpcbind
    #   ansible.builtin.systemd:
    #     name: rpcbind
    #     state: restarted
    #     enabled: true
    #     daemon_reload: true
    #   listen: restart_rpcbind
