---
- name: Configure Linux host
  hosts: all
  become: true
  pre_tasks:
    - name: Update package cache
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false

- name: Configure Linux host
  hosts: all
  become: true
  roles:
    - base

- name: Setup users
  hosts:
    - server
    - nfs_client
  become: true
  roles:
    - users

- name: Configure web_servers
  hosts: server
  become: true
  roles:
    - web_servers

- name: Setup nfs server
  hosts: server
  become: true
  roles:
    - nfs_server

- name: Setup nfs client
  hosts: nfs_client
  become: true
  roles:
    - nfs_client
