- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    recurse: "{{ item.recurse | default(omit) }}"
    owner: nginx
    group: nginx
    mode: "{{ item.mode | default(omit) }}"
    modification_time: preserve
    access_time: preserve
  loop: "{{ web_servers_dirs }}"
  notify:
    - restart_nginx

# REVIEW ok to use name instead of owner/group?
- name: Copy files/templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0644"
  loop: "{{ web_servers_templates }}"
  notify:
    - restart_nginx

- name: Open port 80
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
