# TODO refactor to be able to be used on both server and client

users_groups:
  - name: developers
    gid: 2000 # To be tested
  - name: testers
    gid: 2100 # To be tested
  - name: users
    gid: 4100
  - name: john
    gid: 4000
  - name: sftp_users

users_users:
  - name: john
    uid: 4000
    sudo: true
    group: john
    groups:
      - developers
      - users
      - sftp_users
    password: "$6$rounds=656000$mysecretsalt$L5TfnY7pEWOF0TQfksow3vO3hizg7G.P7sECrIdg8nEyz2jLgO59o3doQcnI/2qMdFYIH1J1HYyXuzPDfIryN."
  - name: jane
    uid: 4100
    group: users
    groups:
      - testers
      - sftp_users

users_regex:
  - regexp: ^(#?PermitRootLogin)+\s*
    line: "PermitRootLogin no"
  - regexp: ^(#?Subsystem)+\s*
    line: "Subsystem      sftp    /usr/libexec/openssh/sftp-server"
  - regexp: ^(#?PasswordAuthentication)+\s*
    line: "PasswordAuthentication no"
