# Create groups =============================
- name: Create developers group
  ansible.builtin.group:
    name: developers

- name: Create testers group
  ansible.builtin.group:
    name: testers

- name: Create users group
  ansible.builtin.group:
    name: users
    gid: 4100

- name: Create john group
  ansible.builtin.group:
    name: john
    gid: 4000

# Users =====================================
# TODO copy content of ssh file
- name: Create user John
  ansible.builtin.user:
    name: john
    uid: 4000
    group: john
    groups:
      - developers
      - users
    shell: /bin/bash
    password: '$6$rounds=656000$mysecretsalt$L5TfnY7pEWOF0TQfksow3vO3hizg7G.P7sECrIdg8nEyz2jLgO59o3doQcnI/2qMdFYIH1J1HYyXuzPDfIryN.'

- name: Create user Jane
  ansible.builtin.user:
    name: jane
    uid: 4100
    group: users
    groups: testers
    shell: /bin/bash

# SSH keys ==================================
- name: Set authorized key John
  ansible.posix.authorized_key:
    user: john
    state: present
    key: "{{ lookup('file', '/home/fredrik/.ssh/id_rsa.pub') }}"

- name: Set authorized key Jane
  ansible.posix.authorized_key:
    user: jane
    state: present
    key: "{{ lookup('file', '/home/fredrik/.ssh/id_rsa.pub') }}"

# Create sudo entry for John ================
- name: Add John to sudoers
  ansible.builtin.copy:
    dest: /etc/sudoers.d/john
    content: 'john ALL=(ALL) NOPASSWD: ALL' # TODO create file instead
    owner: root
    group: root
    mode: '0440'

# Prevent root login ========================
- name: Disable Root Login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^(#?PermitRootLogin)+\s*
    line: 'PermitRootLogin no'
    state: present
    backup: true
  become: true
  notify:
    - restart_ssh
