- name: Create groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    gid: "{{ item.gid | default(omit) }}"
  loop: "{{ users_groups }}"

- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.gid | default(omit) }}"
    group: "{{ item.group }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    password: "{{ item.password | default(omit) }}"
  loop: "{{ users_users }}"

- name: Add ssh key
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '/home/fredrik/.ssh/id_rsa.pub') }}"
  loop: "{{ users_users }}"

- name: Add users to sudoers
  when: item.sudo | default(false) | bool
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.name }} ALL=(ALL) ALL"
    owner: root
    group: root
    mode: "0440"
  loop: "{{ users_users }}"

# REVIEW Should it be here?
- name: Disable Root Login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^(#?PermitRootLogin)+\s*
    line: "PermitRootLogin no"
    state: present
    backup: true
  become: true
  notify:
    - restart_ssh
