- name: Install packages
  ansible.builtin.package:
    name: "{{ base_packages }}"

- name: Disable SELinux
  ansible.posix.selinux:
    state: permissive
    policy: targeted
    update_kernel_param: true

- name: Set system time
  become: true
  community.general.timezone:
    name: "{{ base_timezone }}"

- name: Copy templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: "0644"
  loop: "{{ base_templates }}"
