- name: Install needed packages
  ansible.builtin.package:
    name: "{{ base_packages }}"

- name: Disable SELinux
  ansible.posix.selinux:
    state: permissive
    policy: targeted
    update_kernel_param: true

- name: Set system time
  become: true
  community.general.timezone:
    name: "{{ base_timezone }}"
