---

- name: Install and configure Apache with PHP support
  hosts: all
  become: true
  tasks:

    - name: Install Apache and PHP packages
      ansible.builtin.dnf:
        name:
          - httpd
          - php
          - php-cli
          - php-mysqlnd
        state: present

    - name: Start Apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Open port 80
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true

    - name: Restart Apache to apply PHP changes
      ansible.builtin.service:
        name: httpd
        state: restarted
