---

- name: Install and configure Apache with PHP support
  hosts: all
  become: true
  tasks:

    - name: Update repository index - REDHAT
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Update repository index - DEBIAN
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install Apache and PHP packages - REDHAT
      ansible.builtin.dnf:
        name:
          - httpd
          - php
          - php-cli
          - php-mysqlnd
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install Apache2 and PHP packages - DEBIAN
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start Apache service - REDHAT
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat'

    - name: Open port 80 - REDHAT
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_os_family == 'RedHat'

    - name: Open port 80 - DEBIAN
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_os_family == 'Debian'

    - name: Restart Apache to apply PHP changes - REDHAT
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: ansible_os_family == 'RedHat'
