---

- name: Install and configure Apache with PHP support
  hosts: all
  become: true
  tasks:

    - name: Uninstall Apache and PHP packages - REDHAT
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: absent

    - name: Close port 80 - REDHAT
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: disabled
        immediate: true
      when: ansible_os_family == 'RedHat'

    - name: Close port 80 - DEBIAN
      community.general.ufw:
        rule: deny
        port: '80'
        proto: tcp
      when: ansible_os_family == 'Debian'
