---

- name: Install and configure Apache with PHP support
  hosts: all
  become: true
  vars:
    ansible_become_password: "{{ lookup('file', '~/.vault_key') }}"
  pre_tasks:

    - name: Install updates (Rocky)
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Install updates (Debian)
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_os_family == 'Debian'

- name: Configure web_servers
  hosts: web_servers
  become: true
  tasks:

    - name: Install Apache and PHP packages - REDHAT
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: present
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Install Apache and PHP packages - DEBIAN
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Start Apache service - REDHAT
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat'

    - name: Open port 80 - REDHAT
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_os_family == 'RedHat'

    - name: Open port 80 - DEBIAN
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_os_family == 'Debian'

    - name: Restart Apache to apply PHP changes - REDHAT
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: ansible_os_family == 'RedHat'

- name: Configure db_servers
  hosts: db_servers
  become: true
  tasks:

    - name: Install MariaDB packages - REDHAT
      ansible.builtin.dnf:
        name: mariadb
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install MariaDB packages - DEBIAN
      ansible.builtin.apt:
        name: mariadb-server
        state: present
      when: ansible_os_family == 'Debian'

- name: Configure file_servers
  hosts: file_servers
  become: true
  tasks:

    - name: Install Samba packages
      ansible.builtin.package:
        name: samba
        state: present
