---

- name: Install and configure Apache with PHP support
  hosts: all
  become: true
  vars:
    ansible_become_password: "{{ lookup('file', '~/.vault_key') }}"
  pre_tasks:

    - name: Install updates (Rocky)
      tags: always
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Install updates (Ubuntu)
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_os_family == 'Debian'

- name: Configure web_servers
  hosts: web_servers
  become: true
  tasks:

    - name: Install Apache and PHP packages (Rocky)
      tags: apache,redhat,rocky,httpd
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: present
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: Install Apache and PHP packages (Ubuntu)
      tags: apache,apache2,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Start Apache service (Rocky)
      tags: apache,redhat,rocky,httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == 'RedHat'

    - name: Open port 80 (Rocky)
      tags: apache,redhat,rocky,httpd
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_os_family == 'RedHat'

    - name: Open port 80 (Ubuntu)
      tags: apache,apache2,ubuntu
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
      when: ansible_os_family == 'Debian'

    - name: Restart Apache to apply PHP changes (Rocky)
      tags: apache,redhat,rocky,httpd
      ansible.builtin.service:
        name: httpd
        state: restarted
      when: ansible_os_family == 'RedHat'

    - name: Copy default html file for site
      tags: apache,apache2,httpd
      ansible.builtin.copy:
        src: "{{ inventory_dir }}/files/default_site.html"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

- name: Configure db_servers
  hosts: db_servers
  become: true
  tasks:

    - name: Install MariaDB packages (Rocky)
      tags: mariadb,redhat,rocky,db
      ansible.builtin.dnf:
        name: mariadb
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install MariaDB packages (Ubuntu)
      tags: mariadb,debian,ubuntu,db
      ansible.builtin.apt:
        name: mariadb-server
        state: present
      when: ansible_os_family == 'Debian'

- name: Configure file_servers
  hosts: file_servers
  become: true
  tasks:

    - name: Install Samba packages
      tags: samba,redhat,rocky,file
      ansible.builtin.package:
        name: samba
        state: present
